name: dspace-handle-server

services:

  dspace-handle-server:
    container_name: dspace-handle-server
    image: ${IMAGE_FULL_TAG}
    build:
      context: .
      args:
        - PRIMARY_SERVER=${PRIMARY_SERVER}
        - DUAL_STACK_SERVER=${DUAL_STACK_SERVER}
        - IP_ADDRESS=${IP_ADDRESS}
        - BIND_IP=${BIND_IP}
        - TCP_UDP_PORT=${TCP_UDP_PORT}
        - HTTP_PORT=${HTTP_PORT}
        - LOG_ACCESS=${LOG_ACCESS}
        - LOG_ROTATION_FREQUENCY_SHORT=${LOG_ROTATION_FREQUENCY_SHORT}
        - SITE_VERSION_SERIAL_NUMBER=${SITE_VERSION_SERIAL_NUMBER}
        - SERVER_DESCRIPTION=${SERVER_DESCRIPTION}
        - ORG_NAME=${ORG_NAME}
        - ORG_CONTACT_PERSON=${ORG_CONTACT_PERSON}
        - ORG_CONTACT_PHONE=${ORG_CONTACT_PHONE}
        - ORG_CONTACT_EMAIL=${ORG_CONTACT_EMAIL}
        - DISABLE_UDP=${DISABLE_UDP}
        - ENCRYPT_SERVER_KEY=${ENCRYPT_SERVER_KEY}
        - ENCRYPT_ADMIN_KEY=${ENCRYPT_ADMIN_KEY}
        - HANDLE_PREFIX=${HANDLE_PREFIX}
        - LOG_ROTATION_FREQUENCY_LONG=${LOG_ROTATION_FREQUENCY_LONG}
        - DSPACE_SERVER_URL=${DSPACE_SERVER_URL}
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${TCP_UDP_PORT}:${TCP_UDP_PORT}
    environment:
      BIND_IP: ${BIND_IP}
      HTTP_PORT: ${HTTP_PORT}
      LOG_ACCESS: ${LOG_ACCESS}
      TCP_UDP_PORT: ${TCP_UDP_PORT}
      HANDLE_PREFIX: ${HANDLE_PREFIX}
      LOG_ROTATION_FREQUENCY_LONG: ${LOG_ROTATION_FREQUENCY_LONG}
      DSPACE_SERVER_URL: ${DSPACE_SERVER_URL}